<!DOCTYPE html>
<html lang="en">

<head>
    <title>Animex - Product Detail Page</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="assets/img/apple-icon.png">
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">

    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/templatemo.css">
    <link rel="stylesheet" href="assets/css/custom.css">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="assets/css/fontawesome.min.css">

    <!-- Slick -->
    <link rel="stylesheet" type="text/css" href="assets/css/slick.min.css">
    <link rel="stylesheet" type="text/css" href="assets/css/slick-theme.css">
<!--
    



-->
</head>

<?php
echo '<body>';
echo '<!-- Start Top Nav -->';
echo '<nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">';
echo '<div class="container text-light">';
echo '<div class="w-100 d-flex justify-content-between">';
echo '<div>';
echo '<i class="fa fa-envelope mx-2"></i>';
echo '<a class="navbar-sm-brand text-light text-decoration-none">animex@gmail.com</a>';
echo '<i class="fa fa-phone mx-2"></i>';
echo '<a class="navbar-sm-brand text-light text-decoration-none">010-020-0340</a>';
echo '</div>';
echo '<div>';
echo '<a class="text-light" href="https://fb.com/templatemo" target="_blank" rel="sponsored"><i class="fab fa-facebook-f fa-sm fa-fw me-2"></i></a>';
echo '<a class="text-light" href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram fa-sm fa-fw me-2"></i></a>';
echo '<a class="text-light" href="https://twitter.com/" target="_blank"><i class="fab fa-twitter fa-sm fa-fw me-2"></i></a>';
echo '<a class="text-light" href="https://www.linkedin.com/" target="_blank"><i class="fab fa-linkedin fa-sm fa-fw"></i></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '<!-- Close Top Nav -->';
echo '';
echo '';
echo '<!-- Header -->';
echo '<nav class="navbar navbar-expand-lg navbar-light shadow">';
echo '<div class="container d-flex justify-content-between align-items-center">';
echo '';
echo '<a class="navbar-brand text-success logo h1 align-self-center" href="index.php">';
echo 'Animex';
echo '</a>';
echo '';
echo '<button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '';
echo '<div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">';
echo '<div class="flex-fill">';
echo '<ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="index.php">Home</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="about.php">About</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="shop.php">Shop</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="contact.php">Contact</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '<div class="navbar align-self-center d-flex">';
echo '<div class="d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3">';
echo '<div class="input-group">';
echo '<input type="text" class="form-control" id="inputMobileSearch" placeholder="Search ...">';
echo '<div class="input-group-text">';
echo '<i class="fa fa-fw fa-search"></i>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<a class="nav-icon d-none d-lg-inline" href="#" data-bs-toggle="modal" data-bs-target="#templatemo_search">';
echo '<i class="fa fa-fw fa-search text-dark mr-2"></i>';
echo '</a>';
echo '<a class="nav-icon position-relative text-decoration-none" href="#">';
echo '<i class="fa fa-fw fa-cart-arrow-down text-dark mr-1"></i>';
echo '<span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark">7</span>';
echo '</a>';
echo '<a class="nav-icon position-relative text-decoration-none" href="#">';
echo '<i class="fa fa-fw fa-user text-dark mr-3"></i>';
echo '<span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark">+99</span>';
echo '</a>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</nav>';
echo '<!-- Close Header -->';
echo '';
echo '<!-- Modal -->';
echo '<div class="modal fade bg-white" id="templatemo_search" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">';
echo '<div class="modal-dialog modal-lg" role="document">';
echo '<div class="w-100 pt-1 mb-5 text-right">';
echo '<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>';
echo '</div>';
echo '<form action="" method="get" class="modal-content modal-body border-0 p-0">';
echo '<div class="input-group mb-2">';
echo '<input type="text" class="form-control" id="inputModalSearch" name="q" placeholder="Search ...">';
echo '<button type="submit" class="input-group-text bg-success text-light">';
echo '<i class="fa fa-fw fa-search text-white"></i>';
echo '</button>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '';
echo '<!-- Open Content -->';
echo '<section class="bg-light">';
echo '<div class="container pb-5">';
echo '<div class="row">';
echo '<div class="col-lg-5 mt-5">';
echo '<div class="card mb-3">';
echo '<img class="card-img img-fluid" src="assets/img/pic2.png" alt="Card image cap" id="product-detail">';
echo '</div>';
echo '<div class="row">';
echo '<!--Start Controls-->';
echo '<div class="col-1 align-self-center">';
echo '<a href="#multi-item-example" role="button" data-bs-slide="prev">';
echo '<i class="text-dark fas fa-chevron-left"></i>';
echo '<span class="sr-only">Previous</span>';
echo '</a>';
echo '</div>';
echo '<!--End Controls-->';
echo '<!--Start Carousel Wrapper-->';
echo '<div id="multi-item-example" class="col-10 carousel slide carousel-multi-item" data-bs-ride="carousel">';
echo '<!--Start Slides-->';
echo '<div class="carousel-inner product-links-wap" role="listbox">';
echo '';
echo '<!--First slide-->';
echo '<div class="carousel-item active">';
echo '<div class="row">';
echo '<div class="col-4">';
echo '<a href="#">';
echo '<img class="card-img img-fluid" src="assets/img/pic4.png" alt="Product Image 1">';
echo '</a>';
echo '</div>';
echo '<div class="col-4">';
echo '<a href="#">';
echo '<img class="card-img img-fluid" src="assets/img/pic5.png" alt="Product Image 2">';
echo '</a>';
echo '</div>';
echo '<div class="col-4">';
echo '<a href="#">';
echo '<img class="card-img img-fluid" src="assets/img/pic6.png" alt="Product Image 3">';
echo '</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!--/.First slide-->';
echo '';
echo '<!--Second slide-->';
echo '<div class="carousel-item">';
echo '<div class="row">';
echo '<div class="col-4">';
echo '<a href="#">';
echo '<img class="card-img img-fluid" src="assets/img/pic60.png" alt="Product Image 4">';
echo '</a>';
echo '</div>';
echo '<div class="col-4">';
echo '<a href="#">';
echo '<img class="card-img img-fluid" src="assets/img/pic65.png" alt="Product Image 5">';
echo '</a>';
echo '</div>';
echo '<div class="col-4">';
echo '<a href="#">';
echo '<img class="card-img img-fluid" src="assets/img/pic66.png" alt="Product Image 6">';
echo '</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!--/.Second slide-->';
echo '';
echo '<!--Third slide-->';
echo '<div class="carousel-item">';
echo '<div class="row">';
echo '<div class="col-4">';
echo '<a href="#">';
echo '<img class="card-img img-fluid" src="assets/img/pic67.png" alt="Product Image 7">';
echo '</a>';
echo '</div>';
echo '<div class="col-4">';
echo '<a href="#">';
echo '<img class="card-img img-fluid" src="assets/img/pic68.png" alt="Product Image 8">';
echo '</a>';
echo '</div>';
echo '<div class="col-4">';
echo '<a href="#">';
echo '<img class="card-img img-fluid" src="assets/img/pic69.png" alt="Product Image 9">';
echo '</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!--/.Third slide-->';
echo '</div>';
echo '<!--End Slides-->';
echo '</div>';
echo '<!--End Carousel Wrapper-->';
echo '<!--Start Controls-->';
echo '<div class="col-1 align-self-center">';
echo '<a href="#multi-item-example" role="button" data-bs-slide="next">';
echo '<i class="text-dark fas fa-chevron-right"></i>';
echo '<span class="sr-only">Next</span>';
echo '</a>';
echo '</div>';
echo '<!--End Controls-->';
echo '</div>';
echo '</div>';
echo '<!-- col end -->';
echo '<div class="col-lg-7 mt-5">';
echo '<div class="card">';
echo '<div class="card-body">';
echo '<h1 class="h2">Sanji</h1>';
echo '<p class="h3 py-2">PHP 2,500.00</p>';
echo '<p class="py-2">';
echo '<i class="fa fa-star text-warning"></i>';
echo '<i class="fa fa-star text-warning"></i>';
echo '<i class="fa fa-star text-warning"></i>';
echo '<i class="fa fa-star text-warning"></i>';
echo '<i class="fa fa-star text-secondary"></i>';
echo '<span class="list-inline-item text-dark">Rating 4.9 | 106 Comments</span>';
echo '</p>';
echo '<ul class="list-inline">';
echo '<li class="list-inline-item">';
echo '<h6>Anime:</h6>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<p class="text-muted"><strong>One Piece</strong></p>';
echo '</li>';
echo '</ul>';
echo '';
echo '<h6>Description:</h6>';
echo '<p>This is a very high quality product. </p>';
echo '<ul class="list-inline">';
echo '<li class="list-inline-item">';
echo '<h6>Stocks:</h6>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<p class="text-muted"><strong>783</strong></p>';
echo '</li>';
echo '</ul>';
echo '';
echo '<h6>Specification:</h6>';
echo '<ul class="list-unstyled pb-3">';
echo '<li>High Quality</li>';
echo '<li>Unbreakable</li>';
echo '<li>Many color choices</li>';
echo '</ul>';
echo '';
echo '<form action="" method="GET">';
echo '<input type="hidden" name="product-title" value="Activewear">';
echo '<div class="row">';
echo '<div class="col-auto">';
echo '<ul class="list-inline pb-3">';
echo '<li class="list-inline-item">Size :';
echo '<input type="hidden" name="product-size" id="product-size" value="S">';
echo '</li>';
echo '<li class="list-inline-item"><span class="btn btn-success btn-size">S</span></li>';
echo '<li class="list-inline-item"><span class="btn btn-success btn-size">M</span></li>';
echo '<li class="list-inline-item"><span class="btn btn-success btn-size">L</span></li>';
echo '<li class="list-inline-item"><span class="btn btn-success btn-size">XL</span></li>';
echo '</ul>';
echo '</div>';
echo '<div class="col-auto">';
echo '<ul class="list-inline pb-3">';
echo '<li class="list-inline-item text-right">';
echo 'Quantity';
echo '<input type="hidden" name="product-quanity" id="product-quanity" value="1">';
echo '</li>';
echo '<li class="list-inline-item"><span class="btn btn-success" id="btn-minus">-</span></li>';
echo '<li class="list-inline-item"><span class="badge bg-secondary" id="var-value">1</span></li>';
echo '<li class="list-inline-item"><span class="btn btn-success" id="btn-plus">+</span></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="row pb-3">';
echo '<div class="col d-grid">';
echo '<button type="submit" class="btn btn-success btn-lg" name="submit" value="buy">Buy</button>';
echo '</div>';
echo '<div class="col d-grid">';
echo '<button type="submit" class="btn btn-success btn-lg" name="submit" value="addtocard">Add To Cart</button>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- Close Content -->';
echo '';
echo '<!-- Start Article -->';
echo '<section class="py-5">';
echo '<div class="container">';
echo '<div class="row text-left p-2 pb-3">';
echo '<h4>Related Products</h4>';
echo '</div>';
echo '';
echo '<!--Start Carousel Wrapper-->';
echo '<div id="carousel-related-product">';
echo '';
echo '<div class="p-2 pb-3">';
echo '<div class="product-wap card rounded-0">';
echo '<div class="card rounded-0">';
echo '<img class="card-img rounded-0 img-fluid" src="assets/img/pic30.png">';
echo '<div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">';
echo '<ul class="list-unstyled">';
echo '<li><a class="btn btn-success text-white" href="shop-single.php"><i class="far fa-heart"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="far fa-eye"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="fas fa-cart-plus"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="card-body">';
echo '<a href="shop-single.php" class="h3 text-decoration-none">Vegeta</a>';
echo '<ul class="w-100 list-unstyled d-flex justify-content-between mb-0">';
echo '<li>Resin</li>';
echo '<li class="pt-2">';
echo '<span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>';
echo '</li>';
echo '</ul>';
echo '<ul class="list-unstyled d-flex justify-content-center mb-1">';
echo '<li>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '</li>';
echo '</ul>';
echo '<p class="text-center mb-0">PHP 2,000.00</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="p-2 pb-3">';
echo '<div class="product-wap card rounded-0">';
echo '<div class="card rounded-0">';
echo '<img class="card-img rounded-0 img-fluid" src="assets/img/pic31.png">';
echo '<div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">';
echo '<ul class="list-unstyled">';
echo '<li><a class="btn btn-success text-white" href="shop-single.php"><i class="far fa-heart"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="far fa-eye"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="fas fa-cart-plus"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="card-body">';
echo '<a href="shop-single.php" class="h3 text-decoration-none">Uchiha Itachi</a>';
echo '<ul class="w-100 list-unstyled d-flex justify-content-between mb-0">';
echo '<li>Action Figure</li>';
echo '<li class="pt-2">';
echo '<span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>';
echo '</li>';
echo '</ul>';
echo '<ul class="list-unstyled d-flex justify-content-center mb-1">';
echo '<li>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '</li>';
echo '</ul>';
echo '<p class="text-center mb-0">PHP 2,500.00</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="p-2 pb-3">';
echo '<div class="product-wap card rounded-0">';
echo '<div class="card rounded-0">';
echo '<img class="card-img rounded-0 img-fluid" src="assets/img/pic32.png">';
echo '<div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">';
echo '<ul class="list-unstyled">';
echo '<li><a class="btn btn-success text-white" href="shop-single.php"><i class="far fa-heart"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="far fa-eye"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="fas fa-cart-plus"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="card-body">';
echo '<a href="shop-single.php" class="h3 text-decoration-none">Uchiha Itachi</a>';
echo '<ul class="w-100 list-unstyled d-flex justify-content-between mb-0">';
echo '<li>Resin</li>';
echo '<li class="pt-2">';
echo '<span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>';
echo '</li>';
echo '</ul>';
echo '<ul class="list-unstyled d-flex justify-content-center mb-1">';
echo '<li>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '</li>';
echo '</ul>';
echo '<p class="text-center mb-0">PHP 3,000.00</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="p-2 pb-3">';
echo '<div class="product-wap card rounded-0">';
echo '<div class="card rounded-0">';
echo '<img class="card-img rounded-0 img-fluid" src="assets/img/pic33.png">';
echo '<div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">';
echo '<ul class="list-unstyled">';
echo '<li><a class="btn btn-success text-white" href="shop-single.php"><i class="far fa-heart"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="far fa-eye"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="fas fa-cart-plus"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="card-body">';
echo '<a href="shop-single.php" class="h3 text-decoration-none">Uchiha Itachi</a>';
echo '<ul class="w-100 list-unstyled d-flex justify-content-between mb-0">';
echo '<li>Resin</li>';
echo '<li class="pt-2">';
echo '<span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>';
echo '</li>';
echo '</ul>';
echo '<ul class="list-unstyled d-flex justify-content-center mb-1">';
echo '<li>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '</li>';
echo '</ul>';
echo '<p class="text-center mb-0">PHP 3,000.00</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="p-2 pb-3">';
echo '<div class="product-wap card rounded-0">';
echo '<div class="card rounded-0">';
echo '<img class="card-img rounded-0 img-fluid" src="assets/img/pic34.png">';
echo '<div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">';
echo '<ul class="list-unstyled">';
echo '<li><a class="btn btn-success text-white" href="shop-single.php"><i class="far fa-heart"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="far fa-eye"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="fas fa-cart-plus"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="card-body">';
echo '<a href="shop-single.php" class="h3 text-decoration-none">Yukihira Souma</a>';
echo '<ul class="w-100 list-unstyled d-flex justify-content-between mb-0">';
echo '<li class="">Resin</li>';
echo '<li class="pt-2">';
echo '<span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>';
echo '</li>';
echo '</ul>';
echo '<ul class="list-unstyled d-flex justify-content-center mb-1">';
echo '<li>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '</li>';
echo '</ul>';
echo '<p class="text-center mb-0">PHP 2,000.00</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="p-2 pb-3">';
echo '<div class="product-wap card rounded-0">';
echo '<div class="card rounded-0">';
echo '<img class="card-img rounded-0 img-fluid" src="assets/img/pic35.png">';
echo '<div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">';
echo '<ul class="list-unstyled">';
echo '<li><a class="btn btn-success text-white" href="shop-single.php"><i class="far fa-heart"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="far fa-eye"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="fas fa-cart-plus"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="card-body">';
echo '<a href="shop-single.php" class="h3 text-decoration-none">Yukihira Souma</a>';
echo '<ul class="w-100 list-unstyled d-flex justify-content-between mb-0">';
echo '<li>Resin</li>';
echo '<li class="pt-2">';
echo '<span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>';
echo '</li>';
echo '</ul>';
echo '<ul class="list-unstyled d-flex justify-content-center mb-1">';
echo '<li>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '</li>';
echo '</ul>';
echo '<p class="text-center mb-0">PHP 3,600.00</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="p-2 pb-3">';
echo '<div class="product-wap card rounded-0">';
echo '<div class="card rounded-0">';
echo '<img class="card-img rounded-0 img-fluid" src="assets/img/pic36.png">';
echo '<div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">';
echo '<ul class="list-unstyled">';
echo '<li><a class="btn btn-success text-white" href="shop-single.php"><i class="far fa-heart"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="far fa-eye"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="fas fa-cart-plus"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="card-body">';
echo '<a href="shop-single.php" class="h3 text-decoration-none">Lelouche</a>';
echo '<ul class="w-100 list-unstyled d-flex justify-content-between mb-0">';
echo '<li>Resin</li>';
echo '<li class="pt-2">';
echo '<span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>';
echo '</li>';
echo '</ul>';
echo '<ul class="list-unstyled d-flex justify-content-center mb-1">';
echo '<li>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '</li>';
echo '</ul>';
echo '<p class="text-center mb-0">PHP 3,000.00</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="p-2 pb-3">';
echo '<div class="product-wap card rounded-0">';
echo '<div class="card rounded-0">';
echo '<img class="card-img rounded-0 img-fluid" src="assets/img/pic37.png">';
echo '<div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">';
echo '<ul class="list-unstyled">';
echo '<li><a class="btn btn-success text-white" href="shop-single.php"><i class="far fa-heart"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="far fa-eye"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="fas fa-cart-plus"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="card-body">';
echo '<a href="shop-single.php" class="h3 text-decoration-none">L</a>';
echo '<ul class="w-100 list-unstyled d-flex justify-content-between mb-0">';
echo '<li>Action Figure</li>';
echo '<li class="pt-2">';
echo '<span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>';
echo '</li>';
echo '</ul>';
echo '<ul class="list-unstyled d-flex justify-content-center mb-1">';
echo '<li>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '</li>';
echo '</ul>';
echo '<p class="text-center mb-0">PHP 1,999.00</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="p-2 pb-3">';
echo '<div class="product-wap card rounded-0">';
echo '<div class="card rounded-0">';
echo '<img class="card-img rounded-0 img-fluid" src="assets/img/pic38.png">';
echo '<div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">';
echo '<ul class="list-unstyled">';
echo '<li><a class="btn btn-success text-white" href="shop-single.php"><i class="far fa-heart"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="far fa-eye"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="fas fa-cart-plus"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="card-body">';
echo '<a href="shop-single.php" class="h3 text-decoration-none">Ichigo</a>';
echo '<ul class="w-100 list-unstyled d-flex justify-content-between mb-0">';
echo '<li>Resin</li>';
echo '<li class="pt-2">';
echo '<span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>';
echo '</li>';
echo '</ul>';
echo '<ul class="list-unstyled d-flex justify-content-center mb-1">';
echo '<li>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '</li>';
echo '</ul>';
echo '<p class="text-center mb-0">PHP 2,650.00</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="p-2 pb-3">';
echo '<div class="product-wap card rounded-0">';
echo '<div class="card rounded-0">';
echo '<img class="card-img rounded-0 img-fluid" src="assets/img/pic39.png">';
echo '<div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">';
echo '<ul class="list-unstyled">';
echo '<li><a class="btn btn-success text-white" href="shop-single.php"><i class="far fa-heart"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="far fa-eye"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="fas fa-cart-plus"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="card-body">';
echo '<a href="shop-single.php" class="h3 text-decoration-none">Priest</a>';
echo '<ul class="w-100 list-unstyled d-flex justify-content-between mb-0">';
echo '<li>Action Figure</li>';
echo '<li class="pt-2">';
echo '<span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>';
echo '</li>';
echo '</ul>';
echo '<ul class="list-unstyled d-flex justify-content-center mb-1">';
echo '<li>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '</li>';
echo '</ul>';
echo '<p class="text-center mb-0">PHP 3,400.00</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="p-2 pb-3">';
echo '<div class="product-wap card rounded-0">';
echo '<div class="card rounded-0">';
echo '<img class="card-img rounded-0 img-fluid" src="assets/img/pic40.png">';
echo '<div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">';
echo '<ul class="list-unstyled">';
echo '<li><a class="btn btn-success text-white" href="shop-single.php"><i class="far fa-heart"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="far fa-eye"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="fas fa-cart-plus"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="card-body">';
echo '<a href="shop-single.php" class="h3 text-decoration-none">L</a>';
echo '<ul class="w-100 list-unstyled d-flex justify-content-between mb-0">';
echo '<li>Action Figure</li>';
echo '<li class="pt-2">';
echo '<span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>';
echo '</li>';
echo '</ul>';
echo '<ul class="list-unstyled d-flex justify-content-center mb-1">';
echo '<li>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '</li>';
echo '</ul>';
echo '<p class="text-center mb-0">PHP 3,600.00</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="p-2 pb-3">';
echo '<div class="product-wap card rounded-0">';
echo '<div class="card rounded-0">';
echo '<img class="card-img rounded-0 img-fluid" src="assets/img/pic41.png">';
echo '<div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">';
echo '<ul class="list-unstyled">';
echo '<li><a class="btn btn-success text-white" href="shop-single.php"><i class="far fa-heart"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="far fa-eye"></i></a></li>';
echo '<li><a class="btn btn-success text-white mt-2" href="shop-single.php"><i class="fas fa-cart-plus"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="card-body">';
echo '<a href="shop-single.php" class="h3 text-decoration-none">Wolverine</a>';
echo '<ul class="w-100 list-unstyled d-flex justify-content-between mb-0">';
echo '<li>Resin</li>';
echo '<li class="pt-2">';
echo '<span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>';
echo '<span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>';
echo '</li>';
echo '</ul>';
echo '<ul class="list-unstyled d-flex justify-content-center mb-1">';
echo '<li>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-warning fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '<i class="text-muted fa fa-star"></i>';
echo '</li>';
echo '</ul>';
echo '<p class="text-center mb-0">PHP 2,900.00</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '</section>';
echo '<!-- End Article -->';
echo '';
echo '';
echo '<!-- Start Footer -->';
echo '<footer class="bg-dark" id="tempaltemo_footer">';
echo '<div class="container">';
echo '<div class="row">';
echo '';
echo '<div class="col-md-4 pt-5">';
echo '<h2 class="h2 text-success border-bottom pb-3 border-light logo">Animex</h2>';
echo '<ul class="list-unstyled text-light footer-link-list">';
echo '<li>';
echo '<i class="fas fa-map-marker-alt fa-fw"></i>';
echo 'Gasan, Marinduque, Phil.';
echo '</li>';
echo '<li>';
echo '<i class="fa fa-phone fa-fw"></i>';
echo '<a class="text-decoration-none" href="tel:010-020-0340">010-020-0340</a>';
echo '</li>';
echo '<li>';
echo '<i class="fa fa-envelope fa-fw"></i>';
echo '<a class="text-decoration-none" href="mailto:info@company.com">animex@gmail.com</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '';
echo '<div class="col-md-4 pt-5">';
echo '<h2 class="h2 text-light border-bottom pb-3 border-light">Products</h2>';
echo '<ul class="list-unstyled text-light footer-link-list">';
echo '<li><a class="text-decoration-none" href="#">Action Figure</a></li>';
echo '<li><a class="text-decoration-none" href="#">Figures</a></li>';
echo '</ul>';
echo '</div>';
echo '';
echo '<div class="col-md-4 pt-5">';
echo '<h2 class="h2 text-light border-bottom pb-3 border-light">Further Info</h2>';
echo '<ul class="list-unstyled text-light footer-link-list">';
echo '<li><a class="text-decoration-none" href="#">Home</a></li>';
echo '<li><a class="text-decoration-none" href="#">About Us</a></li>';
echo '<li><a class="text-decoration-none" href="#">Shop Locations</a></li>';
echo '<li><a class="text-decoration-none" href="#">FAQs</a></li>';
echo '<li><a class="text-decoration-none" href="#">Contact</a></li>';
echo '</ul>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<div class="row text-light mb-4">';
echo '<div class="col-12 mb-3">';
echo '<div class="w-100 my-3 border-top border-light"></div>';
echo '</div>';
echo '<div class="col-auto me-auto">';
echo '<ul class="list-inline text-left footer-icons">';
echo '<li class="list-inline-item border border-light rounded-circle text-center">';
echo '<a class="text-light text-decoration-none" target="_blank" href="http://facebook.com/"><i class="fab fa-facebook-f fa-lg fa-fw"></i></a>';
echo '</li>';
echo '<li class="list-inline-item border border-light rounded-circle text-center">';
echo '<a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/"><i class="fab fa-instagram fa-lg fa-fw"></i></a>';
echo '</li>';
echo '<li class="list-inline-item border border-light rounded-circle text-center">';
echo '<a class="text-light text-decoration-none" target="_blank" href="https://twitter.com/"><i class="fab fa-twitter fa-lg fa-fw"></i></a>';
echo '</li>';
echo '<li class="list-inline-item border border-light rounded-circle text-center">';
echo '<a class="text-light text-decoration-none" target="_blank" href="https://www.linkedin.com/"><i class="fab fa-linkedin fa-lg fa-fw"></i></a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '<div class="col-auto">';
echo '<label class="sr-only" for="subscribeEmail">Email address</label>';
echo '<div class="input-group mb-2">';
echo '<input type="text" class="form-control bg-dark border-light" id="subscribeEmail" placeholder="Email address">';
echo '<div class="input-group-text btn-success text-light">Subscribe</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="w-100 bg-black py-3">';
echo '<div class="container">';
echo '<div class="row pt-2">';
echo '<div class="col-12">';
echo '<p class="text-left text-light">';
echo 'Copyright &copy; 2022';

echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</footer>';
?>
    <!-- End Footer -->

    <!-- Start Script -->
    <script src="assets/js/jquery-1.11.0.min.js"></script>
    <script src="assets/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="assets/js/bootstrap.bundle.min.js"></script>
    <script src="assets/js/templatemo.js"></script>
    <script src="assets/js/custom.js"></script>
    <!-- End Script -->

    <!-- Start Slider Script -->
    <script src="assets/js/slick.min.js"></script>
    <script>
        $('#carousel-related-product').slick({
            infinite: true,
            arrows: false,
            slidesToShow: 4,
            slidesToScroll: 3,
            dots: true,
            responsive: [{
                    breakpoint: 1024,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 3
                    }
                },
                {
                    breakpoint: 600,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 3
                    }
                },
                {
                    breakpoint: 480,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 3
                    }
                }
            ]
        });
    </script>
    <!-- End Slider Script -->

</body>

</html>